### ISSUE TITLE
Support running "terraform get"

### ISSUE THREAD

**Issue by jonathanmyers** [dpires/jenkins-terraform-plugin#1]
Current behavior:  Running the plugin with a terraform configuration that uses modules errors out since `terraform get` has not been run.  I don't see a way to add this command prior to the terraform apply that the plugin triggers.

Desired behavior: `terraform get` is always executed before `terraform apply`.  It's an idempotent operation and reasonably fast, so running every time shouldn't be an issue.

**Comment by misteritguru** [comment]
I too have just discovered this. It seems like it would be 'trivial' to add the line terraform get, before terrafom apply, but trying to decipher code in a language you do not speak is hard.

https://github.com/dpires/jenkins-terraform-plugin/blob/5aa7b5929eab7a5a467f0323fbdda4de0237ec79/src/main/java/org/jenkinsci/plugins/terraform/TerraformBuildWrapper.java -- I have a feeling that in this where it seems your constructing the command line, a call to terraform get would solve this issue - Just a guess, please don't flame me :)

**Comment by pmoosh** [comment]
+1

**Comment by dpires** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Terraform+Plugin

I have added support for running get by default, and an optional -update flag.

**Comment by pmoosh** [comment]
@dpires +1 and a big thanks
