### ISSUE TITLE
The terraform run does not inherit the env variables (parameters) set by the job

### ISSUE THREAD

**Issue by AbraxasJung** [dpires/jenkins-terraform-plugin#2]
Using a parameterized build, the terraform execution does not appear to "see" environment variables from parameters.

Example: Set parameter of TF_VAR_NAME with value of derp

This should set the value of var.NAME during the terraform run but it does not. 

These parameters can be referenced in the Resource Variables section of the plugin with NAME = "$TF_VAR_NAME" in the Resource Variables section, but it's not as ideal.

Works fine and sets var.NAME properly when I launch terraform in Execute Script section of Build, but the plugin is a better option.

**Comment by dpires** [comment]
In version 1.0.2 parameterize build env variables are accessible.

1) Declare your variables in a resource (variable "VAR" { } )
2) In the resource variables section, add your variable (VAR="$BUILD_PARAM")
3) In your resource reference your variable (option="${var.VAR}")

I hope this helps.
