### ISSUE TITLE
more a question

### ISSUE THREAD

**Issue by pmoosh** [dpires/jenkins-terraform-plugin#3]
Hi working with plugin, but I seem to quite understand something:

Get works nicely the modules are "downloaded" into $WORKSPACE/terraform. But then it fails because it is looking for the config files  $WORKSPACE/terraform-plugin although I set the  Configuration Path to "terraform"

Does it run the script in the wrong dir?

[terraform] $ 
/var/lib/jenkins/tools/org.jenkinsci.plugins.terraform.TerraformInstallation/Terraform_0.6.16/terraform get -update
Get: file:///jenkinsdatadrive/jenkins/jobs/test-tf/workspace/terraform/rds (update)
....
Get: file:///jenkinsdatadrive/jenkins/jobs/test-tf/workspace/terraform/teradata (update)
[terraform-plugin] $ /var/lib/jenkins/tools/org.jenkinsci.plugins.terraform.TerraformInstallation/Terraform_0.6.16/terraform apply -input=false -state=/var/lib/jenkins/jobs/test-tf/workspace/terraform-plugin/terraform-plugin.tfstate -var-file=/var/lib/jenkins/jobs/test-tf/workspace/terraform-plugin/variables4987469359746446352.tfvars
[31m**Error loading config: No Terraform configuration files found in directory: /jenkinsdatadrive/jenkins/jobs/test-tf/workspace/terraform-plugin**

**Comment by dpires** [comment]
Did you try setting the workspace to terraform-plugin? That is where the conf files are if you are using an inline configuration. Everything is in a single workspace/path which is terraform-plugin.

I haven't tried loading modules into a separate path.

**Comment by pmoosh** [comment]
I  set it to terraform, which is where the *.tf files are in git. I can try to create a project named terraform-plugin and what happens. Will let you when I get a chance.

**Comment by CloudSurgeon** [comment]
experiencing the same thing. No matter the Configuration Path I specify, it always looks in the same folder for the config files:
/var/lib/jenkins/workspace/<JOBNAME>/terraform-plugin

**Comment by dpires** [comment]
Definitely a bug. I have a fix for file-based configurations, just working/testing the inline configurations. Hopefully have a fix shortly

**Comment by CloudSurgeon** [comment]
sweet. just started leveraging the plug-in today. good stuff

**Comment by dpires** [comment]
I have just released a fix (1.0.6) which fixes the modules issue.
I have verified both inline and path-based configurations work with remote modules (git etc.) and local path modules.
